### ISSUE TITLE
Issue while setting up the env

### ISSUE THREAD

**Issue by KOMNOOB** [Deveshjoshi101/StudyPal#13]
![image](https://github.com/Deveshjoshi101/StudyPal/assets/92045934/997e407d-04d0-45f7-80cb-d1a5f5dc20b6)

The log file contents : 
0 verbose cli C:\Program Files\nodejs\node.exe C:\Users\K OMM\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
1 info using npm@8.15.0
2 info using node@v16.13.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:C:\Users\K OMM\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 28ms
6 timing config:load:builtin Completed in 29ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:C:\Users\K OMM\studypal\.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:C:\Users\K OMM\.npmrc Completed in 0ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:C:\Users\K OMM\AppData\Roaming\npm\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 37ms
19 timing npm:load:configload Completed in 37ms
20 timing npm:load:mkdirpcache Completed in 1ms
21 timing npm:load:mkdirplogs Completed in 0ms
22 verbose title npm install
23 verbose argv "install"
24 timing npm:load:setTitle Completed in 1ms
25 timing config:load:flatten Completed in 3ms
26 timing npm:load:display Completed in 4ms
27 verbose logfile logs-max:10 dir:C:\Users\K OMM\AppData\Local\npm-cache\_logs
28 verbose logfile C:\Users\K OMM\AppData\Local\npm-cache\_logs\2023-06-02T05_59_44_267Z-debug-0.log
29 timing npm:load:logFile Completed in 5ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 49ms
33 timing arborist:ctor Completed in 1ms
34 silly logfile start cleaning logs, removing 1 files
35 timing arborist:ctor Completed in 0ms
36 timing idealTree:init Completed in 8ms
37 timing idealTree:userRequests Completed in 0ms
38 silly idealTree buildDeps
39 timing idealTree:#root Completed in 0ms
40 timing idealTree:buildDeps Completed in 1ms
41 timing idealTree:fixDepFlags Completed in 0ms
42 timing idealTree Completed in 11ms
43 timing reify:loadTrees Completed in 12ms
44 timing reify:diffTrees Completed in 0ms
45 silly reify moves {}
46 timing reify:retireShallow Completed in 46ms
47 timing reify:createSparse Completed in 0ms
48 timing reify:loadBundles Completed in 0ms
49 silly audit report null
50 timing reify:audit Completed in 1ms
51 timing reify:unpack Completed in 0ms
52 timing reify:unretire Completed in 0ms
53 timing build:queue Completed in 0ms
54 timing build:deps Completed in 1ms
55 timing build Completed in 1ms
56 timing reify:build Completed in 1ms
57 timing reify:trash Completed in 0ms
58 silly logfile done cleaning log files
59 timing reify:save Completed in 3ms
60 timing reify Completed in 144ms
61 timing command:install Completed in 147ms
62 verbose stack Error: ENOENT: no such file or directory, open 'C:\Users\K OMM\studypal\package.json'
63 verbose cwd C:\Users\K OMM\studypal
64 verbose Windows_NT 10.0.22000
65 verbose node v16.13.0
66 verbose npm  v8.15.0
67 error code ENOENT
68 error syscall open
69 error path C:\Users\K OMM\studypal/package.json
70 error errno -4058
71 error enoent ENOENT: no such file or directory, open 'C:\Users\K OMM\studypal\package.json'
72 error enoent This is related to npm not being able to find a file.
72 error enoent
73 verbose exit -4058
74 timing npm Completed in 2458ms
75 verbose code -4058
76 error A complete log of this run can be found in:
76 error     C:\Users\K OMM\AppData\Local\npm-cache\_logs\2023-06-02T05_59_44_267Z-debug-0.log

**Comment by Deveshjoshi101** [comment]
Hi yes the project has just started. The files are not there. I am working on them and by the end of the day the files will be available.
